### ISSUE TITLE
About supporting Procedural Generation

### ISSUE THREAD

**Issue by albertcity** [aistairc/virtualhome_aist#22]
Hello!
I am finding some envrionment to generate synthetic data for training an VLM. I have read your paper and find `virtualhome_aist` really helpful for me, since it supports lots of animated actions. 
However, `virtualhome_aist` only support 7 scenes from virtualhome v2.2, which is not suitable to large-scale generation.
I have noted that virtualhome v.2.3 has implemented procedural generation of new scenes, therefore I am wondering if it possible to combine the advantages of both？(i.e. procedural generation from virtualhome v2.2 and actions&KGs from virtualhome_aist)?
Best regards.

**Comment by Ease112** [comment]
Hi @albertcity 
Thank you for your interest in our project.
In conclusion, it is not easy.
We started developing VirtualHome-AIST more than three years ago, but VirtualHome 2.3 was not released at that time.
So, VirtualHome-AIST is based on 2.2.
Migrating to 2.2 and 2.3 is not easy because they have significantly different directory structures.
In addition, most of the new features of 2.3 could not be reproduced because it contains many bugs. [[my report](https://github.com/xavierpuigf/virtualhome/issues/86)]
Therefore, we have not migrated to 2.3.

Instead of migration from 2.2 to 2.3, we proposed different approaches: (1) automatically generating action scripts from natural language and (2) combining generated KGs to create long scenarios.
- Jin Aoyama, Takeshi Morita, Takanori Ugai, Shusaku Egami, Ken Fukuda: Automatic Action Script Generation to Improve Execution Rate based on LLM in VirtualHome, Proceedings of the 12th International Joint Conference on Knowledge Graphs (IJCKG2023), 2023 [[paper](https://ijckg2023.knowledge-graph.jp/pages/proc/paper_16.pdf)][[code](https://github.com/JinAoyama/actionscript_generation_in_vh)]
- Shusaku Egami, Satoshi Nishimura, Ken Fukuda: A Framework for Constructing and Augmenting Knowledge Graphs using Virtual Space: Towards Analysis of Daily Activities, Proceedings of the 33rd IEEE International Conference on Tools with Artificial Intelligence (ICTAI2021), pp.1226-1230, 2021 [[paper](https://doi.org/10.1109/ICTAI52525.2021.00194)] [[code](https://github.com/aistairc/Virtualhome2kg)]

Furthermore, we have published datasets generated by VirtualHome-AIST+VirtualHome2KG.
- Takanori Ugai, Shusaku Egami, Swe Nwe Nwe Htun, Kouji Kozaki, Takahiro Kawamura, Ken Fukuda: Synthetic Multimodal Dataset for Empowering Safety and Well-being in Home Environments, Embodied AI Workshop 2024 in conjunction with The IEEE/CVF Conference on Computer Vision and Pattern Recognition 2024 (CVPR2024) [[preprint](https://arxiv.org/abs/2401.14743)] [[dataset](https://github.com/KnowledgeGraphJapan/KGRC-RDF/tree/kgrc4si)]
- Shusaku Egami, Takanori Ugai, Swe Nwe Nwe Htun, Ken Fukuda: VHAKG: A Multi-modal Knowledge Graph Based on Synchronized Multi-view Videos of Daily Activities, Proceedings of the 33rd ACM International Conference on Information and Knowledge Management (CIKM2024), to appear, 2024.10 [[preprint](https://arxiv.org/abs/2408.14895)] [[dataset](https://github.com/aistairc/vhakg)]

I hope this helps you.

**Comment by albertcity** [comment]
Thanks a lot for your detailed reply!  I will checkout these listed paper:)
